apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: silverbullet-ssh
spec:
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: kv/nekropolis/silverbullet/silverbullet-ssh
        property: id_ed25519
    - secretKey: id_ed25519.pub
      remoteRef:
        key: kv/nekropolis/silverbullet/silverbullet-ssh
        property: id_ed25519.pub
    - secretKey: known_hosts
      remoteRef:
        key: kv/nekropolis/silverbullet/silverbullet-ssh
        property: known_hosts
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: silverbullet-ssh
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s

